explanations = {
    "total_passes": ["Total passes that took place this game", "General"],
    "total_hits": ["Total number of hits that took place in a game (using hit detection*)", "General"],
    "total_dribble_conts": ["This is the second, third, … touch of a dribble", "General"],
    "total_aerials": ["Total number of aerials that took place this game", "General"],
    "total_dribbles": ["Total number of dribbles that took place in a game", "General"],
    "useful hits": ["Average distance the ball went after being hit before being touched by another player", "General"],
    "turnovers": ["When the opposite team hits the ball twice after you had hit it and therefore have lost possession", "Turnovers"],
    "turnovers_on_my_half": ["When a turnover occurs but on the defending half", "Turnovers"],
    "turnovers_on_their_half": ["When a turnover occurs but on the opponents half", "Turnovers"],
    "won_turnovers": ["You are the first hit that caused a turnover of the other team", "Turnovers"],
    "possession_time": ["Time you as a player had the ball.  This does continue until someone not you hits the ballor play is stopped.", "Turnovers"],
    "average_speed": ["The average speed of your car over the entire game.", "Averages"],
    "average_hit_distance": ["Average distance the ball went after being hit before being touched by another player", "Averages"],
    "average_distance_from_center": ["Average distance for this player from the team's center.", "Averages"],
    "boost_usage": ["Total boost used over a game. Accurate within 3% in the worst case.", "Boost"],
    "num_small_boosts": ["The number of small boost pads you collect.", "Boost"],
    "num_large_boosts": ["The number of large boost pads you collect.", "Boost"],
    "num_stolen_boosts": ["The number of large pads you take on the enemy\'s half (note this is not context specific).", "Boost"],
    "wasted_collection": ["Boost picked up that goes beyond 100%. For instance if you have 95 boost and pick up a 100 pad, you just wasted 95 boost.", "Boost"],
    "wasted_usage": ["Boost used while you are supersonic", "Boost"],
    "time_full_boost": ["Time in the game where you have 100 boost on your meter", "Boost"],
    "time_low_boost": ["Time in the game where you have <25 boost on your meter", "Boost"],
    "time_no_boost": ["Time in the game where you have 0 boost on your meter.", "Boost"],
    "time_on_ground": ["Time in the game where you are on the ground", "Tendencies"],
    "time_low_in_air": ["Time you spent above ground but below the max height of double jumping (roughly goal height)", "Tendencies"],
    "time_in_defending_half": ["Time the car is in your defending half", "Tendencies"],
    "time_in_attacking_half": ["Time the car is in your opponents half", "Tendencies"],
    "time_in_defending_third": [""]
}
