explanations = {
    "total_passes": ["Total passes that took place this game", "General"],
    "hits": ["Total number of hits that took place in a game (using hit detection*)", "General"],
    "total_dribble_conts": ["This is the second, third, … touch of a dribble", "General"],
    "aerials": ["Total number of aerials that took place this game", "General"],
    "total_dribbles": ["Total number of dribbles that took place in a game", "General"],
    "useful_hits": ["Average distance the ball went after being hit before being touched by another player", "General"],
    "is_keyboard": ["If the player is using a keyboard.", "General"],
    "turnovers": ["When the opposite team hits the ball twice after you had hit it and therefore have lost possession", "Turnovers"],
    "turnovers_on_my_half": ["When a turnover occurs but on the defending half", "Turnovers"],
    "turnovers_on_their_half": ["When a turnover occurs but on the opponents half", "Turnovers"],
    "won_turnovers": ["You are the first hit that caused a turnover of the other team", "Turnovers"],
    "possession_time": ["Time you as a player had the ball.  This does continue until someone not you hits the ballor play is stopped.", "Turnovers"],
    "average_speed": ["The average speed of your car over the entire game.", "Averages"],
    "average_hit_distance": ["Average distance the ball went after being hit before being touched by another player", "Averages"],
    "average_distance_from_center": ["Average distance for this player from the team's center.", "Averages"],
    "boost_usage": ["Total boost used over a game. Accurate within 3% in the worst case.", "Boost"],
    "num_small_boosts": ["The number of small boost pads you collect.", "Boost"],
    "num_large_boosts": ["The number of large boost pads you collect.", "Boost"],
    "num_stolen_boosts": ["The number of large pads you take on the enemy\'s half (note this is not context specific).", "Boost"],
    "wasted_collection": ["Boost picked up that goes beyond 100%. For instance if you have 95 boost and pick up a 100 pad, you just wasted 95 boost.", "Boost"],
    "wasted_usage": ["Boost used while you are supersonic", "Boost"],
    "time_full_boost": ["Time in the game where you have 100 boost on your meter", "Boost"],
    "time_low_boost": ["Time in the game where you have <25 boost on your meter", "Boost"],
    "time_no_boost": ["Time in the game where you have 0 boost on your meter.", "Boost"],
    "time_on_ground": ["Time in the game where you are on the ground", "Tendencies"],
    "time_low_in_air": ["Time you spent above ground but below the max height of double jumping (roughly goal height)", "Tendencies"],
    "time_in_defending_half": ["Time the car is in your defending half", "Tendencies"],
    "time_in_attacking_half": ["Time the car is in your opponents half", "Tendencies"],
    "time_in_defending_third": ["Time the car is in your defending third.", "Tendencies"],
    "time_in_neutral_third": ["Time you spent in the midfield.", "Tendencies"],
    "time_in_attacking_third": ["Time you spent in the enemy third of the field.", "Tendencies"],
    "time_behind_ball": ["(< ball) Time you are between the ball and your own goal.'", "Tendencies"],
    "time_in_font_of_ball": ["(> ball) Time you are between the ball and the enemy goal.", "Tendencies"],
    "time_closest_to_ball": ["No one is closer to the ball than you.", "Tendencies"],
    "time_furthest_from_ball": ["No one is further from the ball than you.", "Tendencies"],
    "time_close_to_ball": ["This distance is equivalent to the width of the goal. It is essentially a ball chase timer.", "Tendencies"],
    "time_closest_to_team_center": ["Time when a player is closest to the center of a team", "Tendencies"],
    "time_furthest_from_team_center": ["Time when a player is furthest to the center of a team", "Tendencies"],
    "ball_hit_forward": ["Summed distance of hits towards opponent goal.", "Distance"],
    "ball_hit_backward": ["Summed distance of hits towards own goal.", "Distance"],
    "time_at_boost_speed": ["Time at a speed only reachable by using boost (or dodges).", "Speed"],
    "time_at_slow_speed": ["Half max car speed without boost.", "Speed"],
    "time_at_super_sonic": ["time at max car speed. Trail is showing.", "Speed"]
}
